version = 0.1

[ner-drugs]
[ner-drugs.deploy]
[ner-drugs.deploy.parameters]
stack_name = "NER-Spacy-Drugs"
s3_bucket = "ner-spacy-drugs-dev"
s3_prefix = "dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides=[]